workflows:
  version: 2
  build-on-schedule:
    jobs:
      - build
    # The cron format is:
    # min (0-59) hour (0-23) monthday (1-31) month (1-12) weekday (0-6, 0=Sun)
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only:
                - master

jobs:
  build:
    filter:
      branches:
        only:
          - master
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - deploy:
            name: Deploy
            command: |
              git config --global user.email "cs5129606@gmail.com"
              git config --global user.name "shijiezhou1"
              git init
              git add -A
              git commit -m 'deploy [ci skip]'
              git push -f git@github.com:shijiezhou1/vue-app.git master:gh-pages

